kind: pipeline
name: Build

steps:
  - name: docker  
    image: plugins/docker
    settings:
      username: nologin
      password:
        from_secret: RG_SECRET
      registry: rg.nl-ams.scw.cloud
      repo: rg.nl-ams.scw.cloud/revlabs/heating
      tags: latest
