kind: pipeline
name: Build

steps:
  - name: Run
    image: python:3.9
    commands:
      - pip install meross-iot click requests
      - python heating.py
    environment:
        MEROSS_EMAIL:
          from_secret: MEROSS_EMAIL
        MEROSS_PASSWORD:
          from_secret: MEROSS_PASSWORD
        SCHEDULE_URL:
          from_secret: SCHEDULE_URL